### ISSUE TITLE
The SDU.cpp is not adapted for charlie

### ISSUE THREAD

**Issue by CptHolzschnauz** [telit/arduino-charlie#2]
Using the SDU lib makes the compiler warn

/Arduino15/packages/Telit-Board/hardware/samd/1.0.1/libraries/SDU/src/SDU.cpp:44:4: error: #error "Unsupported board!"
   #error "Unsupported board!"

**Comment by fabiopi-tlt** [comment]
hello,
it is a matter of rebuilding SDUBoot in the extras and provide the header file in SDU.cpp. We will look into it as soon as possible

**Comment by CptHolzschnauz** [comment]
Yes. It needs a bootcode for your board. Thx!

**Comment by fabiopi-tlt** [comment]
Hello, I tried rebuilding the bootcode but the size is bigger than expected: it results in a binary of 16936 bytes, which is more than the sduBoot array size defined in SDU.cpp. Are you familiar with the sduBoot build? 
I built the sketch for the MKRZERO board, but the resulting header file is still bigger than the one provided SAMD boards. Am I missing some optimization option? The same result occurs with Arduino IDE and arduino-cli, on both Windows and Linux OSes. 
For example, the provided mkrzero.h file size is 91.415 bytes, while the one I generate has a size of more than 103kB....

In any way, I managed to make it work by increasing the bootcode size to 0x6000 for the charlie in SDU.cpp and in SDUBoot.ino, but there is a non-negligible waste of memory for the sketches using SDU. Any clues?

**Comment by CptHolzschnauz** [comment]
Hello! No, unfortunately i'm not. I can just trying but surely not better than you.
Anyhow, very cool to get a reaction! Thx

**Comment by fabiopi-tlt** [comment]
I opened a request on [Arduino forum](https://forum.arduino.cc/t/sduboot-rebuild-binary-size-on-mkrzero/912225,) but for the moment, I received no answer. I will wait for some time, then procede with the workaround for a preliminary release. Better a bit of overhead than no functionality at all :)

**Comment by fabiopi-tlt** [comment]
@CptHolzschnauz new release with the workaround included for SDU. SBU boot code has been added as well in the libraries.
SBU and SSU temporarily removed because of a currently missing feature.
